inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/**/*'

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Security/Open:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: false